plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

allprojects {
    apply plugin: 'java'

    group = 'fr.milekat'
    version = '1.2.0-SNAPSHOT'

    repositories {
        mavenCentral()
        maven { url = "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/" }
        maven { url = "https://libraries.minecraft.net/" }
        maven { url = "https://jitpack.io" }
        maven { url = "https://repo.ranull.com/maven/external/" }
        maven {
            url = uri("https://maven.pkg.github.com/tutur1004/MilekatUtils")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }
        maven {
            url = uri("https://maven.pkg.github.com/tutur1004/MileNpc")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }
        maven { url = "https://repo.fancyplugins.de/releases" }
    }

    dependencies {
        //  Annotation
        compileOnly group: 'org.jetbrains', name: 'annotations', version: '24.0.1'

        //  Minecraft
        compileOnly group: 'org.spigotmc', name: 'spigot-api', version: '1.20.6-R0.1-SNAPSHOT'
        compileOnly group: 'com.mojang', name: 'authlib', version: '1.6.25'

        //  Milekat
        compileOnly group: 'fr.milekat', name: 'npc-api', version: '1.0.0-SNAPSHOT'
    }

    processResources {
        filesMatching('plugin.yml') {
            expand 'pluginVersion': project.version
        }
    }

    ext {
        githubOwner = 'tutur1004'
        repository = 'MileShops'
    }
}

jar {
    from('src/main/java') {
        include "fr/milekat/shop/storage/adapter/sql/shop_schema.sql"
    }
    actions = [] as List<Action<? super Task>>
    dependsOn('shadowJar')
}

shadowJar {
    getArchiveClassifier().set(null)
}

dependencies {
    implementation project('shops-api')

    //  Utils
    implementation group: 'fr.milekat', name: 'milekat-utils', version: '1.2.0-SNAPSHOT'
    implementation group: 'fr.mrmicky', name: 'FastInv', version: '3.0.4'
    compileOnly group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.15.2'
    compileOnly group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: '2.15.2'
    compileOnly group: 'com.fasterxml.jackson.dataformat', name: 'jackson-dataformat-yaml', version: '2.15.2'

    //  Storage clients
    compileOnly group: 'com.zaxxer', name: 'HikariCP', version: '4.0.3'
    compileOnly group: 'mysql', name: 'mysql-connector-java', version: '8.0.33'
    compileOnly group: 'org.mariadb.jdbc', name: 'mariadb-java-client', version: '3.1.2'
    compileOnly group: 'org.postgresql', name: 'postgresql', version: '42.5.4'
    compileOnly group: 'co.elastic.clients', name: 'elasticsearch-java', version: '8.13.0'
}