plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.2.0'
}

allprojects {
    apply plugin: 'java'

    group = 'fr.milekat'
    version = '1.5.0-SNAPSHOT'

    repositories {
        mavenCentral()
        maven { url = "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/" }
        maven { url = "https://libraries.minecraft.net/" }
        maven {
            url = "https://jitpack.io"
            content {
                excludeGroup "fr.milekat"
            }
        }
        maven { url = "https://repo.ranull.com/maven/external/" }
        maven {
            name = 'papermc'
            url = 'https://repo.papermc.io/repository/maven-public/'
        }
        maven {
            url = uri("https://maven.pkg.github.com/tutur1004/MilekatUtils")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }
        maven {
            url = uri("https://maven.pkg.github.com/tutur1004/MileNpc")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }
        maven { url = "https://repo.fancyplugins.de/releases" }
    }

    dependencies {
        //  Annotation
        compileOnly group: 'org.jetbrains', name: 'annotations', version: '24.0.1'

        //  Minecraft
        compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
    }

    processResources {
        filesMatching('plugin.yml') {
            expand 'pluginVersion': project.version
        }
    }

    ext {
        githubOwner = 'tutur1004'
        repository = 'MileShops'
    }
}

jar {
    from('src/main/java') {
        include "fr/milekat/shop/storage/adapter/sql/shop_schema.sql"
    }
    actions = [] as List<Action<? super Task>>
    dependsOn('shadowJar')
}

shadowJar {
    getArchiveClassifier().set(null)

    relocate 'fr.mrmicky' , 'fr.milekat.shops.libs.fastinv'
}

dependencies {
    implementation project('mile-shops-api')

    //  Milekat
    compileOnly group: 'fr.milekat', name: 'mile-npc-api', version: '1.2.1'
    compileOnly group: 'fr.milekat', name: 'mile-banks-api', version: '1.5.1'

    //  Utils
    compileOnly group: 'fr.milekat', name: 'milekat-utils', version: '1.9.1'
    implementation group: 'fr.mrmicky', name: 'fastinv', version: '3.1.2'

    //  Storage clients
    compileOnly group: 'com.zaxxer', name: 'HikariCP', version: '4.0.3'
    compileOnly group: 'mysql', name: 'mysql-connector-java', version: '8.0.33'
    compileOnly group: 'org.mariadb.jdbc', name: 'mariadb-java-client', version: '3.1.2'
    compileOnly group: 'org.postgresql', name: 'postgresql', version: '42.5.4'

    compileOnly group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.18.3'
    compileOnly group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.18.3'
    compileOnly group: 'com.fasterxml.jackson.dataformat', name: 'jackson-dataformat-yaml', version: '2.18.3'
    compileOnly group: 'co.elastic.clients', name: 'elasticsearch-java', version: '9.1.4'
}