services:
  custom-shops:
    build: .
    container_name: custom-shops
    hostname: custom-shops
    restart: always
    networks:
      - sql
      - elastic
    ports:
      - 25565:25565

networks:
  sql:
    name: sql-network
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
          ip_range: 192.168.10.0/24
  elastic:
    name: elastic-network
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 192.168.30.0/24
          gateway: 192.168.30.1
          ip_range: 192.168.30.0/24