# Debug mode
debug: false

# If false, you will have to set players tags alone
default_tags: true

# Storage system
storage:
  #   Available storage type (Please fill related connection section)
  #   (sql)     |=>  MySQL
  #   (sql)     |=>  MariaDB (Recommended)
  #   (sql)     |=>  Postgres
  #   (NoSQL)   |=>  ElasticSearch
  type: ElasticSearch
  sql:
    prefix: "shop_"
    hostname: "localhost"
    port: "3306"
    database: "minecraft"
    username: "user"
    password: "pass"
  elasticsearch:
    prefix: "shop-"
    hostname: "elasticsearch"
    port: "9200"
    username: "user"
    password: "pass"
  cache:
    # Enable or disable cache (Recommended)
    enabled: true
    # Cache time in seconds (Recommended 300s = 5min)
    time: 300

# Messages
messages:
  prefix: "&6[MileShops] "
  gui:
    commons:
      buttons:
        next:
          title: "&cNext page"
          lore:
            - "&6Click to see"
            - "&6next page"
        previous:
          title: "&cPrevious page"
          lore:
            - "&6Click to see"
            - "&6previous page"
        exit:
          title: "&cClose"
          lore: [ ]
    chest-shop:
      title: "&3Shop <shop_name>"
      buttons:
        mode-chest:
          title: "&eInventory mode"
          lore:
            - "&6This mode only trade items"
            - "&6from your inventory"
            - "&6Click to switch to"
            - "&5Shulker mode"
        mode-shulker:
          title: "&5Inventory mode"
          lore:
            - "&6This mode trade items from"
            - "&6Inventory, EnderChest and Shulkers"
            - "&6Click to switch to"
            - "&eInventory mode"
      messages:
        inventory-space: "&cNot enough space in inventory to receive result"
        no-item: "&cNot enough items"
        trade-result: "&2You trade <first_total_amount>x<first_material>, for <result_total_amount>x<result_material>."
        trade-result-hover:
          - "&6You do this trade <count> times"
          - "&6Trade was <first_amount>x<first_material> for <result_amount>x<result_material>"
    admin-shop:
      title: "&3Editing <shop_name>"

# Tags feature (Advanced users)
tags:
  # If false, you will have to set players tags alone
  enable_builtin_tags: true
  ##############################
  # Advanced users ONLY (This section require a plugin who set tags for players)
  # Need 'enable_builtin_tags' to false
  # Tags must be lowercase and without spaces, only letters and dashes are allowed
  # Tags names length must be between 3 and 16 characters
  ##############################
  custom:
    string: [ "player-name", "player-uuid" ]
    integer: [ ]
    long: [ ]
    double: [ ]
    boolean: [ ]
  ##############################